### ISSUE TITLE
Im terrible at c++

### ISSUE THREAD

**Issue by CrypticKingJoe** [ethanedits/Apex-Legends-SDK#1]
Not sure what im missing here but got a few errors listed below

https://i.imgur.com/025xgA6.png

**Comment by YMY1666527646** [comment]
Hey, man, you can learn the basics first, because no one will feed you with a spoon

> 不确定我在这里遗漏了什么，但在下面列出了一些错误
> 
> https://i.imgur.com/025xgA6.png

Hey, man, you can learn the basics first, because no one will feed you with a spoon

**Comment by YMY1666527646** [comment]
Hi, ethanedits, I read your tutorial and successfully made box ESP, but I don't think it's good enough. Thank you for your release, which will be of great help to me. Thank you

**Comment by CrypticKingJoe** [comment]
> Hey, man, you can learn the basics first, because no one will feed you with a spoon
> 
> > 不确定我在这里遗漏了什么，但在下面列出了一些错误
> > https://i.imgur.com/025xgA6.png
> 
> Hey, man, you can learn the basics first, because no one will feed you with a spoon

I managed to solve it
was simpler than I thought
new issue is this

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'Vector2'	Apex Legends SDK	C:\Users\Source\Desktop\Apex-Legends-SDK-main2\Apex Legends SDK\Apex Legends SDK\Main\Modules\NoRecoil.cpp	14
