### ISSUE TITLE
Nothing shows in Apex

### ISSUE THREAD

**Issue by AlexKKhalifa** [ethanedits/Apex-Legends-SDK#13]
So basically I opened Apex Legends SDK.exe it shows me a command prompt then it closes 
![image](https://user-images.githubusercontent.com/73041668/151715720-6b9522d8-6336-4fbd-a150-0b4eef8977f9.png)

I start Apex Legends, press Insert etc. but nothing shows. Am I missing something? I'm new into this

**Comment by dword64** [comment]
@AlexKKhalifa 

Learn c++: https://www.learncpp.com/

So you might find the issue why its not working :D
