### ISSUE TITLE
there are unlimted errors

### ISSUE THREAD

**Issue by Isakuki** [ethanedits/Apex-Legends-SDK#16]
i downloaded python and directx but your thing doesnt include like half the things i need. Everytime i try to build there is a new error. then when i downloaded the right wdk version it said it couldnt find windows kernel tools. and it also said it was missing another truck of files. idk what to do with this bro ima just delete it.

**Comment by dword64** [comment]
@Isakuki 

How to ask a question or report errors/bugs correctly 

When sending a question, be sure to include as much details as possible. In other words, don't ask to ask just ask (https://dontasktoask.com/) your question. Provide what you have, what you want to achieve and what you don't understand/where you are stuck.

If you plan on sending some code, don't forget to format it like shown below². 

```languagename
Your code here
```

If you're code is too large, i recommend sharing your GitHub³repository (or similar remote git repository). If you don't use git, you can use Replit or Pastebin to send your code.

have a nice weekend and stay safe :D
