### ISSUE TITLE
Could you make a tutorial on how to make a glow esp for APEX ?

### ISSUE THREAD

**Issue by EXC3L-YT** [ethanedits/Apex-Legends-SDK#2]
Hi Ethan I’ve been watching a lot of your python videos for CSGO and that really helped me learn python now is amt to do c++ so can you make a guide on how to make a simple esp ?

**Comment by Inverse25k** [comment]
no

**Comment by Maikull** [comment]
Wtf lmao

**Comment by ethanedits** [comment]
There is python and C++ glow esp in this project, just look around and you should find it :)
