### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by 123123asd346** [ethanedits/Apex-Legends-SDK#8]
why:
![image](https://user-images.githubusercontent.com/96850337/150409793-245c70aa-5893-42ae-8393-59cef1d79be5.png)

**Comment by dword64** [comment]
@123123asd346 Replace inside `ApexDriver.inf` the following code section with the following code below!

```cpp
[Version]
Signature="$WINDOWS NT$"
Class=AKMods ; TODO: edit Class
ClassGuid={2DA5ACE2-36FE-4CD3-BE46-7C078B7ECB14} ; TODO: edit ClassGuid
```

**Comment by MadrisAkb** [comment]
just delete  thé apex driver.inf file and then rebuild then is done

**Comment by ethanedits** [comment]
What @MadrisAkb  said should work.
